from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Request

from api.core.logging import get_logger
from api.models.user import User
from api.services import limiter
from api.v1.dependencies.auth import get_current_user
from api.v1.schemas.input import ChemicalReportRequest
from api.v1.schemas.output import ChemicalReportResponse
from src.generate_report import generate_one_chemical_report

logger = get_logger(__name__)

router = APIRouter(prefix="/reports", tags=["reports"])


@router.post("/generate_report", response_model=ChemicalReportResponse)
@limiter.limit("10/minute")
async def generate_report(
    request: Request,
    report_request: ChemicalReportRequest,
    current_user: User = Depends(get_current_user),
) -> ChemicalReportResponse:
    logger.info(
        "generate_report_started",
        title=report_request.title,
        prompt=report_request.prompt
    )
    
    try:
        report_content = await generate_one_chemical_report(
            prompt=report_request.prompt,
            chemical=report_request.chemical_compound,
        )
        
        logger.info(
            "generate_report_completed",
            title=report_request.title,
            report_length=len(report_content),
        )
        
        return ChemicalReportResponse(
            id=1,  # In a real application, this would be generated by the database
            title=report_request.title,
            content=report_content,
            created_at= datetime.now(),
        )
    
    except Exception as exc:
        logger.error(
            "generate_report_failed",
            title=report_request.title,
            error=str(exc),
        )
        raise HTTPException(status_code=500, detail="Failed to generate report")
